name: Transcribe
# manual trigger
on: 
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 1440
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Install
        run: |
          make deps

      - name: Build ğŸ”§
        env:
          ASSEMBLYAI_KEY: ${{ secrets.ASSEMBLYAI_KEY }}
        run: |
          make transcribe

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add assemblyai
          git commit -a -m "Transcription"

      - name: Deploy ğŸš€
        run: |
          git pull --rebase
          git push